spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alkemy
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true

  application:
    pageSize: 10

loggin:
  level:
    com:
      amazonaws:
        internal:
          InstanceMetadataServiceResourceFetcher: error
        util:
          EC2MetadataUtils: error


amazonProperties:
  endpointUrl: ${AMAZON_S3_ENDPOINT_URL}
  publicKey: ${AMAZON_S3_PUBLIC_KEY}
  secretKey: ${AMAZON_S3_SECRET_KEY}
  bucketName: ${AMAZON_S3_BUCKET_NAME}

springdoc:
  swagger-ui:
    path: /api/docs