spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alkemy
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    continue-on-error: true